#pragma once

#include "Order.hpp"
#include "OrderBook.hpp"
#include "../concurrency/OrderBuffer.hpp"
#include "Trade.hpp"
#include <vector>

class MatchingEngine {
public:
    void run(OrderBuffer& buffer);
private:
    OrderBook orderBook_;
    // Processes an incoming order.
    // Returns a vector of trades generated by the matching.
    std::vector<Trade> processOrder(Order& order);
};
