#pragma once

#include "Order.hpp"
#include "OrderBook.hpp"
#include "Trade.hpp"
#include <vector>

class MatchingEngine {
public:
    // Processes an incoming order.
    // Returns a vector of trades generated by the matching.
    std::vector<Trade> processOrder(Order& order);

private:
    OrderBook orderBook_;
};
